# Generated by Django 4.2.19 on 2025-03-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_incidencia_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(choices=[('plomeria', 'Plomeria'), ('electricidad', 'Electricidad'), ('infraestructura', 'Infraestructura'), ('mantenimiento_equipos', 'Mantenimiento de Equipos'), ('saneamiento', 'Saneamiento'), ('seguridad', 'Seguridad'), ('jardineria', 'Jardineria'), ('agua_potable', 'Sistema de Agua Potable'), ('gas', 'Sistema de Gas'), ('incendios', 'Sistema de Incendios')], max_length=100),
        ),
    ]
