# Generated by Django 4.2.19 on 2025-03-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_incidencia_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='correo',
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('espera', 'Espera'), ('cerrada', 'Cerrada')], default='abierta', max_length=100),
        ),
    ]
