# Generated by Django 4.2.19 on 2025-03-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_incidencia_cliente_remove_incidencia_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencia',
            old_name='usuario_reporte',
            new_name='usuario',
        ),
    ]
