# Generated by Django 4.2.19 on 2025-03-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_rename_usuario_reporte_incidencia_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencia',
            old_name='usuario',
            new_name='usuario_reporte',
        ),
    ]
