# Generated by Django 4.2.19 on 2025-03-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_rename_usuario_incidencia_usuario_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(choices=[('plomeria', 'Plomeria'), ('electricidad', 'Electricidad'), ('infraestructura', 'Infraestructura'), ('mantenimiento_equipos', 'Mantenimiento de Equipos'), ('saneamiento', 'Saneamiento'), ('seguridad', 'Seguridad'), ('jardineria', 'Jardineria'), ('agua_potable', 'Sistema de Agua Potable'), ('gas', 'Sistema de Gas'), ('incendios', 'Sistema de Incendios')], default='plomeria', max_length=50),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
    ]
