# Generated by Django 4.2.19 on 2025-03-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_incidencia_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencia',
            old_name='image',
            new_name='imagen',
        ),
    ]
