# Generated by Django 4.2.19 on 2025-03-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_rename_image_incidencia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
