# Generated by Django 4.2.19 on 2025-03-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_incidencia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='prioridad',
            field=models.CharField(choices=[('3', 'Alta'), ('2', 'Media'), ('1', 'Baja')], default='media', max_length=10),
        ),
    ]
