# Generated by Django 4.2.19 on 2025-03-13 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='reporte_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.material'),
        ),
    ]
