# Generated by Django 4.2.19 on 2025-03-13 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_reporte_reporte_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='reporte_incidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.incidencia'),
        ),
    ]
