# Generated by Django 4.2.19 on 2025-03-13 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_reporte_reporte_incidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='tipo',
        ),
    ]
