# Generated by Django 4.2.19 on 2025-03-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_remove_reporte_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='estado',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
