# Generated by Django 4.2.19 on 2025-05-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='incidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.incidencia'),
        ),
    ]
