# Generated by Django 4.2.19 on 2025-05-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_alter_personal_incidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='incidencia',
        ),
    ]
