# Generated by Django 4.2.19 on 2025-05-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_remove_personal_incidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='personal_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.personal'),
        ),
    ]
