# Generated by Django 4.2.19 on 2025-05-28 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_incidencia_personal_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='personal_asignado',
        ),
        migrations.AddField(
            model_name='personal',
            name='incidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.incidencia'),
        ),
    ]
