# Generated by Django 4.2.19 on 2025-05-29 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_remove_incidencia_personal_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to='usuarios.personal'),
        ),
    ]
