# Generated by Django 4.2.19 on 2025-06-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_respuestasoporte_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='urlAsociated',
            field=models.TextField(default='none'),
        ),
    ]
