# Generated by Django 5.2.17 on 2026-09-20 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_notification_urlasociated'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='prioridad_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='prioridad',
            field=models.CharField(choices=[('3', 'Alta'), ('2', 'Media'), ('1', 'Baja')], default='2', max_length=10),
        ),
        migrations.AlterField(
            model_name='personal',
            name='incidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.incidencia'),
        ),
    ]
