# Generated by Django 5.2.17 on 2026-09-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0034_datos_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('infraestructura', 'Infraestructura'), ('mantenimiento_equipos', 'Mantenimiento de equipos'), ('saneamiento', 'Saneamiento'), ('seguridad', 'Seguridad'), ('jardineria', 'Jardinería'), ('agua_potable', 'Sistema de agua potable'), ('gas', 'Sistema de gas'), ('incendios', 'Sistema de incendios')], default='plomeria', max_length=50),
        ),
    ]
