import urllib.request
r = urllib.request.urlopen('http://127.0.0.1:8801/')
html = r.read().decode()
print('lang=es:', 'lang="es"' in html)
print('sg-login:', 'sg-login' in html)
print('sg-sheet:', 'sg-sheet' in html)
print('sg-field:', 'sg-field' in html)
print('sg-alert:', 'sg-alert' in html)
print('sg-foot:', 'sg-foot' in html)
print('sg-btn:', 'sg-btn' in html)
print('OLD lg-frame:', 'lg-frame' in html)
print('OLD lg-zones:', 'lg-zones' in html)
print('data-sg-toggle-password:', 'data-sg-toggle-password' in html)
print('page_head title:', 'sg-page-head__title' in html)
print('Status:', r.status)
